name: Move Issue to Done on Checklist Completion

on:
  issues:
    types: [edited]

jobs:
  move_to_done:
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'edited' && github.event.issue.state == 'open' }}

    steps:
    - name: Check if all checklist items are completed
      id: check_completion
      run: |
        CHECKBOXES=$(echo "${{ github.event.issue.body }}" | grep -o '\[.\]' | wc -l)
        CHECKED=$(echo "${{ github.event.issue.body }}" | grep -o '\[x\]' | wc -l)
        if [ "$CHECKBOXES" -ne "$CHECKED" ]; then
          echo "Not all checklist items are completed."
          exit 1
        fi

    - name: Move Issue to Done Column
      if: steps.check_completion.outcome == 'success'
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        REPO=${{ github.repository }}
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        COLUMN_ID=YOUR_DONE_COLUMN_ID  # Replace with the actual ID of the 'Done' column
        curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/projects/columns/$COLUMN_ID/cards \
          -d '{"content_id": '$ISSUE_NUMBER', "content_type": "Issue"}
